version: '3'
 
services:
  ticketweb:
    container_name: flask-web
    image: flask-web:rds
    build:
      context : .
    ports:
      - 5000:5000 
    restart: on-failure
    networks:
      - net
  nginx:
   image: nginx:latest
   volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"
   depends_on:
    - ticketweb
   ports:
    - "80:80"
   networks:
      - net
networks:
  net:
